
import { prismaMock } from '../mockPrisma'

import { MODEL_ERROR } from '../../src/common/constants'

import { fetchDashboard } from '../../src/models/dashboard'

describe('fetchDashboard', () => {
  const mockFetchedBreakpoints = [
    {
      breakpoint: 'lg',
      breakpointwidth: 1200,
    },
    {
      breakpoint: 'md',
      breakpointwidth: 996,
    },
    {
      breakpoint: 'sm',
      breakpointwidth: 168,
    },
  ]
  const mockFetchedDashboardItems = [
    {
      id: 19,
      name: 'severity-summary',
      ckey: 'severitiesSummary',
      height: 3,
      width: 6,
      x: 0,
      y: 0,
      prop: 'severitiesSummary',
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [],
    },
    {
      id: 20,
      name: 'asset-risk',
      ckey: 'riskPerAsset',
      height: 3,
      width: 6,
      x: 6,
      y: 0,
      prop: 'riskPerAsset',
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 20,
          x: 6,
          y: 3,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 21,
      name: 'global-rating',
      ckey: 'global',
      height: 3,
      width: 6,
      x: 0,
      y: 3,
      prop: 'global',
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [],
    },
    {
      id: 22,
      name: 'vulnerability-history',
      ckey: 'scanHistory',
      height: 3,
      width: 6,
      x: 6,
      y: 3,
      prop: 'scanHistory',
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 22,
          x: 6,
          y: 6,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 23,
      name: 'vulnerabilities-heat-map',
      ckey: 'likelihoods',
      height: 3,
      width: 6,
      x: 0,
      y: 6,
      prop: 'likelihoods',
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [],
    },
    {
      id: 24,
      name: 'probe-status',
      ckey: 'probe-status',
      height: 3,
      width: 6,
      x: 6,
      y: 6,
      prop: null,
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 24,
          x: 6,
          y: 9,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 25,
      name: 'top-vulnerabilities',
      ckey: 'topVulnerabilities',
      height: 3,
      width: 6,
      x: 0,
      y: 9,
      prop: 'topVulnerabilities',
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [],
    },
    {
      id: 26,
      name: 'project-assignment',
      ckey: 'assignement',
      height: 3,
      width: 6,
      x: 6,
      y: 9,
      prop: 'assignement',
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 26,
          x: 6,
          y: 12,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 27,
      name: 'location-sites',
      ckey: 'locationSites',
      height: 4,
      width: 12,
      x: 0,
      y: 12,
      prop: 'locationSites',
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 27,
          x: 0,
          y: 15,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 28,
      name: 'severity-summary',
      ckey: 'severitiesSummary',
      height: 8,
      width: 12,
      x: 0,
      y: 0,
      prop: 'severitiesSummary',
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [],
    },
    {
      id: 29,
      name: 'asset-risk',
      ckey: 'riskPerAsset',
      height: 8,
      width: 12,
      x: 0,
      y: 8,
      prop: 'riskPerAsset',
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 29,
          x: 0,
          y: 16,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 30,
      name: 'global-rating',
      ckey: 'global',
      height: 8,
      width: 12,
      x: 0,
      y: 16,
      prop: 'global',
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 30,
          x: 0,
          y: 24,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 31,
      name: 'vulnerability-history',
      ckey: 'scanHistory',
      height: 8,
      width: 12,
      x: 0,
      y: 24,
      prop: 'scanHistory',
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 31,
          x: 0,
          y: 32,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 32,
      name: 'vulnerabilities-heat-map',
      ckey: 'likelihoods',
      height: 8,
      width: 12,
      x: 0,
      y: 32,
      prop: 'likelihoods',
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 32,
          x: 0,
          y: 40,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 33,
      name: 'probe-status',
      ckey: 'probe-status',
      height: 8,
      width: 12,
      x: 0,
      y: 40,
      prop: null,
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 33,
          x: 0,
          y: 48,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 34,
      name: 'top-vulnerabilities',
      ckey: 'topVulnerabilities',
      height: 8,
      width: 12,
      x: 0,
      y: 48,
      prop: 'topVulnerabilities',
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 34,
          x: 0,
          y: 56,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 35,
      name: 'project-assignment',
      ckey: 'assignement',
      height: 8,
      width: 12,
      x: 0,
      y: 56,
      prop: 'assignement',
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 35,
          x: 0,
          y: 64,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 36,
      name: 'location-sites',
      ckey: 'locationSites',
      height: 6,
      width: 12,
      x: 0,
      y: 64,
      prop: 'locationSites',
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 36,
          x: null,
          y: null,
          width: null,
          height: null,
          visible: false,
        },
      ],
    },
    {
      id: 10,
      name: 'severity-summary',
      ckey: 'severitiesSummary',
      height: 3,
      width: 5,
      x: 0,
      y: 0,
      prop: 'severitiesSummary',
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [],
    },
    {
      id: 11,
      name: 'global-rating',
      ckey: 'global',
      height: 3,
      width: 2,
      x: 10,
      y: 0,
      prop: 'global',
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [],
    },
    {
      id: 12,
      name: 'asset-risk',
      ckey: 'riskPerAsset',
      height: 3,
      width: 5,
      x: 5,
      y: 0,
      prop: 'riskPerAsset',
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [],
    },
    {
      id: 13,
      name: 'vulnerability-history',
      ckey: 'scanHistory',
      height: 3,
      width: 6,
      x: 0,
      y: 3,
      prop: 'scanHistory',
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 13,
          x: 0,
          y: 5,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 14,
      name: 'vulnerabilities-heat-map',
      ckey: 'likelihoods',
      height: 2,
      width: 4,
      x: 8,
      y: 3,
      prop: 'likelihoods',
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [],
    },
    {
      id: 15,
      name: 'probe-status',
      ckey: 'probe-status',
      height: 2,
      width: 6,
      x: 6,
      y: 5,
      prop: null,
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [],
    },
    {
      id: 16,
      name: 'top-vulnerabilities',
      ckey: 'topVulnerabilities',
      height: 3,
      width: 6,
      x: 0,
      y: 6,
      prop: 'topVulnerabilities',
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 16,
          x: 0,
          y: 8,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 17,
      name: 'project-assignment',
      ckey: 'assignement',
      height: 3,
      width: 6,
      x: 6,
      y: 7,
      prop: 'assignement',
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [],
    },
    {
      id: 18,
      name: 'location-sites',
      ckey: 'locationSites',
      height: 4,
      width: 12,
      x: 0,
      y: 10,
      prop: 'locationSites',
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 18,
          x: 0,
          y: 11,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
    {
      id: 37,
      name: 'assets-count',
      ckey: 'assets-count',
      height: 3,
      width: 6,
      x: 6,
      y: 0,
      prop: null,
      breakpoint: 'md',
      breakpointwidth: 996,
      dashboard_user: [],
    },
    {
      id: 38,
      name: 'assets-count',
      ckey: 'assets-count',
      height: 8,
      width: 12,
      x: 0,
      y: 8,
      prop: null,
      breakpoint: 'sm',
      breakpointwidth: 168,
      dashboard_user: [],
    },
    {
      id: 39,
      name: 'assets-count',
      ckey: 'assets-count',
      height: 2,
      width: 2,
      x: 6,
      y: 3,
      prop: null,
      breakpoint: 'lg',
      breakpointwidth: 1200,
      dashboard_user: [
        {
          user_id: '1a3f30d8-a8fb-4f93-be14-5ba55e5a4bdc',
          dashboard_item_id: 39,
          x: 0,
          y: 3,
          width: null,
          height: null,
          visible: true,
        },
      ],
    },
  ]

  it('should return error if Prisma crash on fetching dashboard items', async () => {

    prismaMock.dashboard_item.groupBy.mockResolvedValue(mockFetchedBreakpoints)

    prismaMock.dashboard_item.findMany.mockRejectedValue(
      new Error('Prisma error')
    )

    expect((await fetchDashboard('goodUserId'))?.error).toBe(MODEL_ERROR)
  })

  it('should return error if Prisma crash on fetching dashboard breakpoints', async () => {

    prismaMock.dashboard_item.groupBy.mockRejectedValue(
      new Error('Prisma error')
    )

    expect((await fetchDashboard('goodUserId'))?.error).toBe(MODEL_ERROR)
  })

  it('should return dashboard items by breakpoints if everything is ok', async () => {

    prismaMock.dashboard_item.groupBy.mockResolvedValue(mockFetchedBreakpoints)

    prismaMock.dashboard_item.findMany.mockResolvedValue(
      mockFetchedDashboardItems
    )

    expect((await fetchDashboard('goodUserId'))?.dashboard).toEqual([
      {
        breakpoint: 'lg',
        breakpointwidth: 1200,
        items: [
          {
            id: 10,
            breakpointWidth: 1200,
            name: 'severity-summary',
            ckey: 'severitiesSummary',
            defaultHeight: 3,
            defaultWidth: 5,
            defaultX: 0,
            defaultY: 0,
            prop: 'severitiesSummary',
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 11,
            breakpointWidth: 1200,
            name: 'global-rating',
            ckey: 'global',
            defaultHeight: 3,
            defaultWidth: 2,
            defaultX: 10,
            defaultY: 0,
            prop: 'global',
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 12,
            breakpointWidth: 1200,
            name: 'asset-risk',
            ckey: 'riskPerAsset',
            defaultHeight: 3,
            defaultWidth: 5,
            defaultX: 5,
            defaultY: 0,
            prop: 'riskPerAsset',
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 13,
            breakpointWidth: 1200,
            name: 'vulnerability-history',
            ckey: 'scanHistory',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 0,
            defaultY: 3,
            prop: 'scanHistory',
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 5,
            visible: true,
          },
          {
            id: 14,
            breakpointWidth: 1200,
            name: 'vulnerabilities-heat-map',
            ckey: 'likelihoods',
            defaultHeight: 2,
            defaultWidth: 4,
            defaultX: 8,
            defaultY: 3,
            prop: 'likelihoods',
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 15,
            breakpointWidth: 1200,
            name: 'probe-status',
            ckey: 'probe-status',
            defaultHeight: 2,
            defaultWidth: 6,
            defaultX: 6,
            defaultY: 5,
            prop: null,
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 16,
            breakpointWidth: 1200,
            name: 'top-vulnerabilities',
            ckey: 'topVulnerabilities',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 0,
            defaultY: 6,
            prop: 'topVulnerabilities',
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 8,
            visible: true,
          },
          {
            id: 17,
            breakpointWidth: 1200,
            name: 'project-assignment',
            ckey: 'assignement',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 6,
            defaultY: 7,
            prop: 'assignement',
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 18,
            breakpointWidth: 1200,
            name: 'location-sites',
            ckey: 'locationSites',
            defaultHeight: 4,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 10,
            prop: 'locationSites',
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 11,
            visible: true,
          },
          {
            id: 39,
            breakpointWidth: 1200,
            name: 'assets-count',
            ckey: 'assets-count',
            defaultHeight: 2,
            defaultWidth: 2,
            defaultX: 6,
            defaultY: 3,
            prop: null,
            breakpoint: 'lg',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 3,
            visible: true,
          },
        ],
      },
      {
        breakpoint: 'md',
        breakpointwidth: 996,
        items: [
          {
            id: 19,
            breakpointWidth: 996,
            name: 'severity-summary',
            ckey: 'severitiesSummary',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 0,
            defaultY: 0,
            prop: 'severitiesSummary',
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 20,
            breakpointWidth: 996,
            name: 'asset-risk',
            ckey: 'riskPerAsset',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 6,
            defaultY: 0,
            prop: 'riskPerAsset',
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: 6,
            userY: 3,
            visible: true,
          },
          {
            id: 21,
            breakpointWidth: 996,
            name: 'global-rating',
            ckey: 'global',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 0,
            defaultY: 3,
            prop: 'global',
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 22,
            breakpointWidth: 996,
            name: 'vulnerability-history',
            ckey: 'scanHistory',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 6,
            defaultY: 3,
            prop: 'scanHistory',
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: 6,
            userY: 6,
            visible: true,
          },
          {
            id: 23,
            breakpointWidth: 996,
            name: 'vulnerabilities-heat-map',
            ckey: 'likelihoods',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 0,
            defaultY: 6,
            prop: 'likelihoods',
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 24,
            breakpointWidth: 996,
            name: 'probe-status',
            ckey: 'probe-status',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 6,
            defaultY: 6,
            prop: null,
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: 6,
            userY: 9,
            visible: true,
          },
          {
            id: 25,
            breakpointWidth: 996,
            name: 'top-vulnerabilities',
            ckey: 'topVulnerabilities',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 0,
            defaultY: 9,
            prop: 'topVulnerabilities',
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 26,
            breakpointWidth: 996,
            name: 'project-assignment',
            ckey: 'assignement',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 6,
            defaultY: 9,
            prop: 'assignement',
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: 6,
            userY: 12,
            visible: true,
          },
          {
            id: 27,
            breakpointWidth: 996,
            name: 'location-sites',
            ckey: 'locationSites',
            defaultHeight: 4,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 12,
            prop: 'locationSites',
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 15,
            visible: true,
          },
          {
            id: 37,
            breakpointWidth: 996,
            name: 'assets-count',
            ckey: 'assets-count',
            defaultHeight: 3,
            defaultWidth: 6,
            defaultX: 6,
            defaultY: 0,
            prop: null,
            breakpoint: 'md',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
        ],
      },
      {
        breakpoint: 'sm',
        breakpointwidth: 168,
        items: [
          {
            id: 28,
            breakpointWidth: 168,
            name: 'severity-summary',
            ckey: 'severitiesSummary',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 0,
            prop: 'severitiesSummary',
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
          {
            id: 29,
            breakpointWidth: 168,
            name: 'asset-risk',
            ckey: 'riskPerAsset',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 8,
            prop: 'riskPerAsset',
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 16,
            visible: true,
          },
          {
            id: 30,
            breakpointWidth: 168,
            name: 'global-rating',
            ckey: 'global',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 16,
            prop: 'global',
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 24,
            visible: true,
          },
          {
            id: 31,
            breakpointWidth: 168,
            name: 'vulnerability-history',
            ckey: 'scanHistory',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 24,
            prop: 'scanHistory',
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 32,
            visible: true,
          },
          {
            id: 32,
            breakpointWidth: 168,
            name: 'vulnerabilities-heat-map',
            ckey: 'likelihoods',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 32,
            prop: 'likelihoods',
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 40,
            visible: true,
          },
          {
            id: 33,
            breakpointWidth: 168,
            name: 'probe-status',
            ckey: 'probe-status',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 40,
            prop: null,
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 48,
            visible: true,
          },
          {
            id: 34,
            breakpointWidth: 168,
            name: 'top-vulnerabilities',
            ckey: 'topVulnerabilities',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 48,
            prop: 'topVulnerabilities',
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 56,
            visible: true,
          },
          {
            id: 35,
            breakpointWidth: 168,
            name: 'project-assignment',
            ckey: 'assignement',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 56,
            prop: 'assignement',
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: 0,
            userY: 64,
            visible: true,
          },
          {
            id: 36,
            breakpointWidth: 168,
            name: 'location-sites',
            ckey: 'locationSites',
            defaultHeight: 6,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 64,
            prop: 'locationSites',
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: false,
          },
          {
            id: 38,
            breakpointWidth: 168,
            name: 'assets-count',
            ckey: 'assets-count',
            defaultHeight: 8,
            defaultWidth: 12,
            defaultX: 0,
            defaultY: 8,
            prop: null,
            breakpoint: 'sm',
            userHeight: null,
            userWidth: null,
            userX: null,
            userY: null,
            visible: null,
          },
        ],
      },
    ])
  })
})
