CREATE TABLE credinfo (
    id SERIAL,
    scan_id integer,
    type character varying,
    auth_method character varying,
    username character varying,
    password character varying,
    port integer,
    security_level character varying,
    auth_algorithm character varying,
    auth_password character varying,
    privacy_algorithm character varying,
    privacy_password character varying,
    private_key TEXT,
    private_key_passphrase character varying,
    user_cert TEXT,
    kdc character varying,
    kdc_port integer,
    kdc_transport character varying,
    realm character varying,
    elevate_privileges_with character varying,
    escalation_password character varying,
    escalation_account character varying,
    bin_directory character varying,
    su_user character varying,
    custom_password_prompt character varying,
    domain character varying,
    ca_crt TEXT
);