-- INITIAL SETUP
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- CREATE TYPES
\i 'docker-entrypoint-initdb.d/types/enums.sql'

-- CREATE TABLES
\i 'docker-entrypoint-initdb.d/tables/alembic_version.sql'
\i 'docker-entrypoint-initdb.d/tables/asset.sql'
\i 'docker-entrypoint-initdb.d/tables/asset_compliance.sql'
\i 'docker-entrypoint-initdb.d/tables/asset_network.sql'
\i 'docker-entrypoint-initdb.d/tables/score_asset.sql'
\i 'docker-entrypoint-initdb.d/tables/score_asset_history.sql'
\i 'docker-entrypoint-initdb.d/tables/asset_server.sql'
\i 'docker-entrypoint-initdb.d/tables/asset_web.sql'
\i 'docker-entrypoint-initdb.d/tables/asset_user.sql'
\i 'docker-entrypoint-initdb.d/tables/asset_building.sql'
\i 'docker-entrypoint-initdb.d/tables/asset_document.sql'
\i 'docker-entrypoint-initdb.d/tables/business_impact.sql'
\i 'docker-entrypoint-initdb.d/tables/cartography.sql'
\i 'docker-entrypoint-initdb.d/tables/cartography_element.sql'
\i 'docker-entrypoint-initdb.d/tables/cipher_suite.sql'
\i 'docker-entrypoint-initdb.d/tables/comment.sql'
\i 'docker-entrypoint-initdb.d/tables/comment_watch.sql'
\i 'docker-entrypoint-initdb.d/tables/company.sql'
\i 'docker-entrypoint-initdb.d/tables/compliance.sql'
\i 'docker-entrypoint-initdb.d/tables/dashboard_item.sql'
\i 'docker-entrypoint-initdb.d/tables/dashboard_user.sql'
\i 'docker-entrypoint-initdb.d/tables/cpe.sql'
\i 'docker-entrypoint-initdb.d/tables/cpe_asset.sql'
\i 'docker-entrypoint-initdb.d/tables/credinfo.sql'
\i 'docker-entrypoint-initdb.d/tables/cvss.sql'
\i 'docker-entrypoint-initdb.d/tables/feared_event.sql'
\i 'docker-entrypoint-initdb.d/tables/group.sql'
\i 'docker-entrypoint-initdb.d/tables/group_asset.sql'
\i 'docker-entrypoint-initdb.d/tables/info.sql'
\i 'docker-entrypoint-initdb.d/tables/ip.sql'
\i 'docker-entrypoint-initdb.d/tables/latest_scan_summary.sql'
\i 'docker-entrypoint-initdb.d/tables/mitre.sql'
\i 'docker-entrypoint-initdb.d/tables/phishing_scenario.sql'
\i 'docker-entrypoint-initdb.d/tables/phishing_scenario_domain.sql'
\i 'docker-entrypoint-initdb.d/tables/port.sql'
\i 'docker-entrypoint-initdb.d/tables/reference.sql'
\i 'docker-entrypoint-initdb.d/tables/result.sql'
\i 'docker-entrypoint-initdb.d/tables/scan_asset.sql'
\i 'docker-entrypoint-initdb.d/tables/scan.sql'
\i 'docker-entrypoint-initdb.d/tables/severity.sql'
\i 'docker-entrypoint-initdb.d/tables/status_update.sql'
\i 'docker-entrypoint-initdb.d/tables/tag.sql'
\i 'docker-entrypoint-initdb.d/tables/user.sql'
\i 'docker-entrypoint-initdb.d/tables/user_group.sql'
\i 'docker-entrypoint-initdb.d/tables/user_session.sql'
\i 'docker-entrypoint-initdb.d/tables/vulnerability_asset.sql'
\i 'docker-entrypoint-initdb.d/tables/vulnerability.sql'
\i 'docker-entrypoint-initdb.d/tables/uri.sql'
\i 'docker-entrypoint-initdb.d/tables/relation.sql'
\i 'docker-entrypoint-initdb.d/tables/request.sql'
\i 'docker-entrypoint-initdb.d/tables/revision.sql'
\i 'docker-entrypoint-initdb.d/tables/response.sql'
\i 'docker-entrypoint-initdb.d/tables/setting.sql'
\i 'docker-entrypoint-initdb.d/tables/store.sql'
\i 'docker-entrypoint-initdb.d/tables/tag_asset.sql'
\i 'docker-entrypoint-initdb.d/tables/probe.sql'
\i 'docker-entrypoint-initdb.d/tables/header.sql'
\i 'docker-entrypoint-initdb.d/tables/business_mission_unit_feared_event_has_business_impact.sql'
\i 'docker-entrypoint-initdb.d/tables/business_mission_unit_has_feared_event.sql'
\i 'docker-entrypoint-initdb.d/tables/asset_mission.sql'
\i 'docker-entrypoint-initdb.d/tables/comment_remediation_project.sql'
\i 'docker-entrypoint-initdb.d/tables/project_priority.sql'
\i 'docker-entrypoint-initdb.d/tables/project_status.sql'
\i 'docker-entrypoint-initdb.d/tables/remediation_project_status_history.sql'
\i 'docker-entrypoint-initdb.d/tables/project_status_workflow.sql'
\i 'docker-entrypoint-initdb.d/tables/remediation_project.sql'
\i 'docker-entrypoint-initdb.d/tables/remediation_project_assignee.sql'
\i 'docker-entrypoint-initdb.d/tables/remediation_project_scope.sql'
\i 'docker-entrypoint-initdb.d/tables/scan_label.sql'

-- ADD CONSTRAINTS
\i 'docker-entrypoint-initdb.d/constraints/independent_constraints.sql'
\i 'docker-entrypoint-initdb.d/constraints/foreign_keys.sql'

-- SET VARIABLES
\i 'docker-entrypoint-initdb.d/vars.sql'

-- CREATE VIEWS
\i 'docker-entrypoint-initdb.d/views/scan_vulnerability_report.sql'
\i 'docker-entrypoint-initdb.d/views/vulnerability_has_cve.sql'
\i 'docker-entrypoint-initdb.d/views/v_remediation_project_summary_list.sql'
\i 'docker-entrypoint-initdb.d/views/v_remediation_project_status_history.sql'
\i 'docker-entrypoint-initdb.d/views/v_remediation_project_comment.sql'
\i 'docker-entrypoint-initdb.d/views/v_project_status_workflow.sql'
\i 'docker-entrypoint-initdb.d/views/v_remediation_project_scope.sql'
\i 'docker-entrypoint-initdb.d/views/v_remediation_project_details.sql'
\i 'docker-entrypoint-initdb.d/views/v_asset_child.sql'
\i 'docker-entrypoint-initdb.d/views/v_grouped_remediation.sql'
\i 'docker-entrypoint-initdb.d/views/v_asset_risk_scores.sql'
\i 'docker-entrypoint-initdb.d/views/v_scan_asset_details.sql'
\i 'docker-entrypoint-initdb.d/views/v_scan_severity_count.sql'

-- CREATE FUNCTIONS
\i 'docker-entrypoint-initdb.d/functions/archive_asset_vuln_project_scope.sql'
\i 'docker-entrypoint-initdb.d/functions/update_scope_item_status.sql'
\i 'docker-entrypoint-initdb.d/functions/update_vulnerability_asset_status.sql'
\i 'docker-entrypoint-initdb.d/functions/set_cluster_id.sql'

-- CREATE TRIGGERS
\i 'docker-entrypoint-initdb.d/triggers/archive_project_scope_before_delete.sql'
\i 'docker-entrypoint-initdb.d/triggers/update_vulnerability_asset_status_with_project_scope_item.sql'
\i 'docker-entrypoint-initdb.d/triggers/vulnerability_cluster_id_after_insert_update.sql'
