/**
 * @typedef {{
 *  id: number,
 *  compliance: string
 *  chapter: string,
 *  chapter_small: string,
 *  title: string,
 *  section: string,
 *  description: string,
 *  non_existant_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  inneffective_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  partially_effective_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  effective_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  docs: string,
 *  asset_id: number,
 *  name: string,
 *  compliance_id: number,
 *  status: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  mitigation: string,
 *  residual_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  response: {text: string, value: string}[]
 * }} compliance
 */

/**
 * @type {compliance[]}
 */
export default [
  {
    asset_id: 92,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 20,
    description:
      'A formal user access provisioning process shall be implemented to assign or revoke user access rights to systems and services.',
    docs: null,
    effective_risk: 'Ok',
    id: 20,
    inneffective_risk: 'Medium',
    mitigation: 'No user',
    name: 'ISO 27001 / Access Control / User access provisioning',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.2.2',
    status: 'High',
    title: 'User access provisioning',
  },
  {
    asset_id: 115,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 25,
    description:
      'Access to information and application system functions shall be restricted in accordance with the access control policy.',
    docs: null,
    effective_risk: 'Ok',
    id: 25,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / Information access restriction',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.4.1',
    status: 'Low',
    title: 'Information access restriction',
  },
  {
    asset_id: 116,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 26,
    description:
      'Where required by the access control policy, access to systems and applications shall be controlled by a secure log-on procedure.',
    docs: null,
    effective_risk: 'Ok',
    id: 26,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / Secure log-on procedures',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.4.2',
    status: 'High',
    title: 'Secure log-on procedures',
  },
  {
    asset_id: 117,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 27,
    description:
      'Password management systems shall be interactive and shall ensure quality passwords.',
    docs: null,
    effective_risk: 'Ok',
    id: 27,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / Password management system',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.4.3',
    status: 'Medium',
    title: 'Password management system',
  },
  {
    asset_id: 118,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 18,
    description:
      'Users shall only be provided with access to the network and network services that they have been specifically authorized to use.',
    docs: null,
    effective_risk: 'Ok',
    id: 18,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Access Control / Access to networks and network services',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.1.2',
    status: 'Low',
    title: 'Access to networks and network services',
  },
  {
    asset_id: 119,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 21,
    description:
      'The allocation and use of privileged access rights shall be restricted and controlled.',
    docs: null,
    effective_risk: 'Ok',
    id: 21,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / Management of privileged access rights',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.2.3',
    status: 'Ok',
    title: 'Management of privileged access rights',
  },
  {
    asset_id: 120,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 19,
    description:
      'A formal user registration and de-registration process shall be implemented to enable assignment of access rights.',
    docs: null,
    effective_risk: 'Ok',
    id: 19,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / User registration and de-registration',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.2.1',
    status: 'Low',
    title: 'User registration and de-registration',
  },
  {
    asset_id: 121,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 24,
    description:
      'The access rights of all employees and external party users to information and information processing facilities shall be removed upon termination of their employment, contract or agreement, or adjusted upon change.',
    docs: null,
    effective_risk: 'Ok',
    id: 24,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / Removal or adjustment of access rights',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.2.6',
    status: 'High',
    title: 'Removal or adjustment of access rights',
  },
  {
    asset_id: 122,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 28,
    description:
      'The use of utility programs that might be capable of overriding system and application controls shall be restricted and tightly controlled.',
    docs: null,
    effective_risk: 'Ok',
    id: 28,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / Use of privileged utility programs',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.4.4',
    status: 'High',
    title: 'Use of privileged utility programs',
  },
  {
    asset_id: 123,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 29,
    description: 'Access to program source code shall be restricted.',
    docs: null,
    effective_risk: 'Ok',
    id: 29,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / Access control to program source code',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.4.5',
    status: 'Medium',
    title: 'Access control to program source code',
  },
  {
    asset_id: 124,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 23,
    description:
      'Asset owners shall review users’ access rights at regular intervals.',
    docs: null,
    effective_risk: 'Ok',
    id: 23,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Access Control / Review of user access rights',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.2.5',
    status: 'Low',
    title: 'Review of user access rights',
  },
  {
    asset_id: 125,
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    compliance: 'ISO 27001',
    compliance_id: 22,
    description:
      'The allocation of secret authentication information shall be controlled through a formal management process.',
    docs: null,
    effective_risk: 'Ok',
    id: 22,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Access Control / Management of secret authentication information of users',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.9.2.4',
    status: 'Medium',
    title: 'Management of secret authentication information of users',
  },
  {
    asset_id: 126,
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    compliance: 'ISO 27001',
    compliance_id: 82,
    description:
      'Employees and contractors using the organization’s information systems and services shall be required to note and report any observed or suspected information security weaknesses in systems or services.',
    docs: null,
    effective_risk: 'Ok',
    id: 82,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Information Security Incident Management / Reporting information security weaknesses',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.16.1.3',
    status: 'Medium',
    title: 'Reporting information security weaknesses',
  },
  {
    asset_id: 127,
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    compliance: 'ISO 27001',
    compliance_id: 83,
    description:
      'Information security events shall be assessed and it shall be decided if they are to be classified as information security incidents.',
    docs: null,
    effective_risk: 'Ok',
    id: 83,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Information Security Incident Management / Assessment of and decision on information security events',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.16.1.4',
    status: 'Low',
    title: 'Assessment of and decision on information security events',
  },
  {
    asset_id: 128,
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    compliance: 'ISO 27001',
    compliance_id: 81,
    description:
      'Information security events shall be reported through appropriate management channels as quickly as possible.',
    docs: null,
    effective_risk: 'Ok',
    id: 81,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Information Security Incident Management / Reporting information security events',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.16.1.2',
    status: 'Low',
    title: 'Reporting information security events',
  },
  {
    asset_id: 129,
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    compliance: 'ISO 27001',
    compliance_id: 84,
    description:
      'Information security incidents shall be responded to in accordance with the documented procedures.',
    docs: null,
    effective_risk: 'Ok',
    id: 84,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Information Security Incident Management / Response to information security incidents',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.16.1.5',
    status: 'Ok',
    title: 'Response to information security incidents',
  },
  {
    asset_id: 130,
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    compliance: 'ISO 27001',
    compliance_id: 86,
    description:
      'The organization shall define and apply procedures for the identification, collection, acquisition and preservation of information, which can serve as evidence.',
    docs: null,
    effective_risk: 'Ok',
    id: 86,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Information Security Incident Management / Collection of evidence',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.16.1.7',
    status: 'High',
    title: 'Collection of evidence',
  },
  {
    asset_id: 131,
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    compliance: 'ISO 27001',
    compliance_id: 93,
    description:
      'Cryptographic controls shall be used in compliance with all relevant agreements, legislation and regulations.',
    docs: null,
    effective_risk: 'Ok',
    id: 93,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Compliance / Regulation of cryptographic controls',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.18.1.5',
    status: 'Low',
    title: 'Regulation of cryptographic controls',
  },
  {
    asset_id: 132,
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    compliance: 'ISO 27001',
    compliance_id: 91,
    description:
      'Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release, in accordance with legislator, regulatory, contractual and business requirements.',
    docs: null,
    effective_risk: 'Ok',
    id: 91,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Compliance / Protection of records',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.18.1.3',
    status: 'Low',
    title: 'Protection of records',
  },
  {
    asset_id: 133,
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    compliance: 'ISO 27001',
    compliance_id: 96,
    description:
      'Information systems shall be regularly reviewed for compliance with the organization’s information security policies and standards.',
    docs: null,
    effective_risk: 'Ok',
    id: 96,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Compliance / Technical compliance review',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.18.2.3',
    status: 'High',
    title: 'Technical compliance review',
  },
  {
    asset_id: 134,
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    compliance: 'ISO 27001',
    compliance_id: 94,
    description:
      'The organization’s approach to managing information security and its implementation (i.e. control objectives, controls, policies, processes and procedures for information security) shall be reviewed independently at planned intervals or when significant changes occur.',
    docs: null,
    effective_risk: 'Ok',
    id: 94,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Compliance / Independent review of information security',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.18.2.1',
    status: 'Ok',
    title: 'Independent review of information security',
  },
  {
    asset_id: 135,
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    compliance: 'ISO 27001',
    compliance_id: 95,
    description:
      'Managers shall regularly review the compliance of information processing and procedures within their area of responsibility with the appropriate security policies, standards and any other security requirements.',
    docs: null,
    effective_risk: 'Ok',
    id: 95,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Compliance / Compliance with security policies and standards',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.18.2.2',
    status: 'Low',
    title: 'Compliance with security policies and standards',
  },
  {
    asset_id: 136,
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    compliance: 'ISO 27001',
    compliance_id: 90,
    description:
      'Appropriate procedures shall be implemented to ensure compliance with legislative, regulatory and contractual requirements related to intellectual property rights and use of proprietary software products.',
    docs: null,
    effective_risk: 'Ok',
    id: 90,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Compliance / Intellectual property rights',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.18.1.2',
    status: 'Medium',
    title: 'Intellectual property rights',
  },
  {
    asset_id: 137,
    chapter: 'Organization of Information Security',
    chapter_small: 'ISO Chapter A.6',
    compliance: 'ISO 27001',
    compliance_id: 1,
    description:
      'Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of the organization’s assets.',
    docs: null,
    effective_risk: 'Ok',
    id: 1,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Organization of Information Security / Segregation of duties',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.6.1.2',
    status: 'Ok',
    title: 'Segregation of duties',
  },
  {
    asset_id: 138,
    chapter: 'Organization of Information Security',
    chapter_small: 'ISO Chapter A.6',
    compliance: 'ISO 27001',
    compliance_id: 2,
    description:
      'Information security should be addressed in project management, regardless of the type of the project',
    docs: null,
    effective_risk: 'Ok',
    id: 2,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Organization of Information Security / Infromation security in project management',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.6.1.5',
    status: 'Ok',
    title: 'Infromation security in project management',
  },
  {
    asset_id: 139,
    chapter: 'Organization of Information Security',
    chapter_small: 'ISO Chapter A.6',
    compliance: 'ISO 27001',
    compliance_id: 3,
    description:
      'A policy and supporting security measures shall be adopted to manage the risks introduced by using mobile devices.',
    docs: null,
    effective_risk: 'Ok',
    id: 3,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Organization of Information Security / Mobile Device Policy',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.6.2.1',
    status: 'Medium',
    title: 'Mobile Device Policy',
  },
  {
    asset_id: 140,
    chapter: 'Human Resources Security',
    chapter_small: 'ISO Chapter A.7',
    compliance: 'ISO 27001',
    compliance_id: 4,
    description:
      'Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations and ethics and shall be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.',
    docs: null,
    effective_risk: 'Ok',
    id: 4,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Human Resources Security / Screening',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.7.1.1',
    status: 'Medium',
    title: 'Screening',
  },
  {
    asset_id: 141,
    chapter: 'Human Resources Security',
    chapter_small: 'ISO Chapter A.7',
    compliance: 'ISO 27001',
    compliance_id: 5,
    description:
      'Management shall require all employees and contractors to apply information security in accordance with the established policies and procedures of the organization.',
    docs: null,
    effective_risk: 'Ok',
    id: 5,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Human Resources Security / Management responsibilities',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.7.2.1',
    status: 'High',
    title: 'Management responsibilities',
  },
  {
    asset_id: 142,
    chapter: 'Human Resources Security',
    chapter_small: 'ISO Chapter A.7',
    compliance: 'ISO 27001',
    compliance_id: 6,
    description:
      'All employees of the organization and, where relevant, contractors shall receive appropriate awareness education and training and regular updates in organizational policies and procedures, as relevant for their job function.',
    docs: null,
    effective_risk: 'Ok',
    id: 6,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Human Resources Security / Information security awareness, education and training',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.7.2.2',
    status: 'Low',
    title: 'Information security awareness, education and training',
  },
  {
    asset_id: 143,
    chapter: 'Human Resources Security',
    chapter_small: 'ISO Chapter A.7',
    compliance: 'ISO 27001',
    compliance_id: 7,
    description:
      'Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, communicated to the employee or contractor and enforced.',
    docs: null,
    effective_risk: 'Ok',
    id: 7,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Human Resources Security / Termination or change of employment responsibilities',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.7.3.1',
    status: 'Low',
    title: 'Termination or change of employment responsibilities',
  },
  {
    asset_id: 144,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: 8,
    description:
      'Assets associated with information and information processing facilities shall be identified and an inventory of these assets shall be drawn up and maintained.',
    docs: null,
    effective_risk: 'Ok',
    id: 8,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Asset Management / Inventory of Assets',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.1.1',
    status: 'Ok',
    title: 'Inventory of Assets',
  },
  {
    asset_id: 145,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: 9,
    description: 'Assets maintained in the inventory shall be owned.',
    docs: null,
    effective_risk: 'Ok',
    id: 9,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Asset Management / Ownership of Assets',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.1.2',
    status: 'Ok',
    title: 'Ownership of Assets',
  },
  {
    asset_id: 146,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: 10,
    description:
      'Rules for the acceptable use of information and of assets associated with information and information processing facilities shall be identified, documented and implemented.',
    docs: null,
    effective_risk: 'Ok',
    id: 10,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Asset Management / Acceptable use of Assets',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.1.3',
    status: 'Ok',
    title: 'Acceptable use of Assets',
  },
  {
    asset_id: 147,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: 11,
    description:
      'All employees and external party users shall return all of the organizational assets in their possession upon termination of their employment, contract or agreement.',
    docs: null,
    effective_risk: 'Ok',
    id: 11,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Asset Management / Return of Assets',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.1.4',
    status: 'Ok',
    title: 'Return of Assets',
  },
  {
    asset_id: 148,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: 12,
    description:
      'Information shall be classified in terms of legal requirements, value, criticality and sensitivity to unauthorized disclosure or modification.',
    docs: null,
    effective_risk: 'Ok',
    id: 12,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Asset Management / Classification of information',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.2.1',
    status: 'High',
    title: 'Classification of information',
  },
  {
    asset_id: 149,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: 13,
    description:
      'An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.',
    docs: null,
    effective_risk: 'Ok',
    id: 13,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Asset Management / Labelling of information',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.2.2',
    status: 'Ok',
    title: 'Labelling of information',
  },
  {
    asset_id: 150,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: 15,
    description:
      'Procedures shall be implemented for the management of removable media* in accordance with the classification scheme adopted by the organization.  *any type of storage device that can be removed from a computer while the system is running (e.g. DVD, BR, USB drives…)',
    docs: null,
    effective_risk: 'Ok',
    id: 15,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Asset Management / Management of removable media',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.3.1',
    status: 'Low',
    title: 'Management of removable media',
  },
  {
    asset_id: 151,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: 16,
    description:
      'Media shall be disposed of securely when no longer required, using formal procedures.',
    docs: null,
    effective_risk: 'Ok',
    id: 16,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Asset Management / Disposal of media',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.3.2',
    status: 'Medium',
    title: 'Disposal of media',
  },
  {
    asset_id: 152,
    chapter: 'Cryptography',
    chapter_small: 'ISO Chapter A.10',
    compliance: 'ISO 27001',
    compliance_id: 30,
    description:
      'A policy on the use of cryptographic controls for protection of information shall be developed and implemented.',
    docs: null,
    effective_risk: 'Ok',
    id: 30,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Cryptography / Policy on the use of cryptographic controls',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.10.1.1',
    status: 'Low',
    title: 'Policy on the use of cryptographic controls',
  },
  {
    asset_id: 153,
    chapter: 'Cryptography',
    chapter_small: 'ISO Chapter A.10',
    compliance: 'ISO 27001',
    compliance_id: 31,
    description:
      'A policy on the use, protection and lifetime of cryptographic keys shall be developed and implemented through their whole lifecycle.',
    docs: null,
    effective_risk: 'Ok',
    id: 31,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Cryptography / Key management',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.10.1.2',
    status: 'Ok',
    title: 'Key management',
  },
  {
    asset_id: 154,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 32,
    description:
      'Security perimeters shall be defined and used to protect areas that contain either sensitive or critical information and information processing facilities.',
    docs: null,
    effective_risk: 'Ok',
    id: 32,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Physical security perimeter',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.1.1',
    status: 'Low',
    title: 'Physical security perimeter',
  },
  {
    asset_id: 155,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 33,
    description:
      'Secure areas shall be protected by appropriate entry controls to ensure that only authorized personnel are allowed access.',
    docs: null,
    effective_risk: 'Ok',
    id: 33,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Physical entry controls',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.1.2',
    status: 'High',
    title: 'Physical entry controls',
  },
  {
    asset_id: 156,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 34,
    description:
      'Physical security for offices, rooms and facilities shall be designed and applied.',
    docs: null,
    effective_risk: 'Ok',
    id: 34,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Securing offices rooms and facilities',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.1.3',
    status: 'Medium',
    title: 'Securing offices rooms and facilities',
  },
  {
    asset_id: 157,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 35,
    description:
      'Physical protection against natural disasters, malicious attack or accidents shall be designed and applied.',
    docs: null,
    effective_risk: 'Ok',
    id: 35,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Protecting against external and environmental threats',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.1.4',
    status: 'High',
    title: 'Protecting against external and environmental threats',
  },
  {
    asset_id: 158,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 36,
    description:
      'Procedures for working in secure areas shall be designed and applied.',
    docs: null,
    effective_risk: 'Ok',
    id: 36,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Working in secure areas',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.1.5',
    status: 'Low',
    title: 'Working in secure areas',
  },
  {
    asset_id: 159,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 37,
    description:
      'Access points such as delivery and loading areas and other points where unauthorized persons could enter the premises shall be controlled and, if possible, isolated from information processing facilities to avoid unauthorized access.',
    docs: null,
    effective_risk: 'Ok',
    id: 37,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Delivery and loading areas',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.1.6',
    status: 'Ok',
    title: 'Delivery and loading areas',
  },
  {
    asset_id: 160,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 38,
    description:
      'Equipment shall be sited and protected to reduce the risks from environmental threats and hazards, and opportunities for unauthorized access.',
    docs: null,
    effective_risk: 'Ok',
    id: 38,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Equipment siting and protection',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.1',
    status: 'High',
    title: 'Equipment siting and protection',
  },
  {
    asset_id: 161,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 39,
    description:
      'Equipment shall be protected from power failures and other disruptions caused by failures in supporting utilities.',
    docs: null,
    effective_risk: 'Ok',
    id: 39,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Supporting utilities',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.2',
    status: 'Low',
    title: 'Supporting utilities',
  },
  {
    asset_id: 162,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 40,
    description:
      'Power and telecommunications cabling carrying data or supporting information services shall be protected from interception, interference or damage.',
    docs: null,
    effective_risk: 'Ok',
    id: 40,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Physical and Environmental Security / Cabling security',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.3',
    status: 'Low',
    title: 'Cabling security',
  },
  {
    asset_id: 163,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 41,
    description:
      'Equipment shall be correctly maintained to ensure its continued availability and integrity.',
    docs: null,
    effective_risk: 'Ok',
    id: 41,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Equipment maintenance',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.4',
    status: 'Medium',
    title: 'Equipment maintenance',
  },
  {
    asset_id: 164,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 42,
    description:
      'Equipment, information or software shall not be taken off-site without prior authorization.',
    docs: null,
    effective_risk: 'Ok',
    id: 42,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Physical and Environmental Security / Removal of assets',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.5',
    status: 'Medium',
    title: 'Removal of assets',
  },
  {
    asset_id: 165,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 43,
    description:
      'Security shall be applied to off-site assets taking into account the different risks of working outside the organization\'s premises',
    docs: null,
    effective_risk: 'Ok',
    id: 43,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Security of equipment and assets off premises',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.6',
    status: 'Ok',
    title: 'Security of equipment and assets off premises',
  },
  {
    asset_id: 166,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 44,
    description:
      'All items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.',
    docs: null,
    effective_risk: 'Ok',
    id: 44,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Secure Disposal or reuse of equipment',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.7',
    status: 'Ok',
    title: 'Secure Disposal or reuse of equipment',
  },
  {
    asset_id: 167,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: 45,
    description:
      'Users shall ensure that unattended equipment has appropriate protection.',
    docs: null,
    effective_risk: 'Ok',
    id: 45,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Physical and Environmental Security / Unattended user equipment',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.8',
    status: 'Low',
    title: 'Unattended user equipment',
  },
  {
    asset_id: 168,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: 50,
    description:
      'Detection, prevention and recovery controls to protect against malware shall be implemented.',
    docs: null,
    effective_risk: 'Ok',
    id: 50,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Operations Security / Controls against Malware',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.2.1',
    status: 'Low',
    title: 'Controls against Malware',
  },
  {
    asset_id: 169,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: 51,
    description:
      'Backup copies of information, software and system images shall be taken and tested regularly in accordance with an agreed backup policy.',
    docs: null,
    effective_risk: 'Ok',
    id: 51,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Operations Security / Information Backup',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.3.1',
    status: 'Ok',
    title: 'Information Backup',
  },
  {
    asset_id: 170,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: 52,
    description:
      'Event logs recording user activities, exceptions, faults and information security events shall be produced, kept and regularly reviewed.',
    docs: null,
    effective_risk: 'Ok',
    id: 52,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Operations Security / Event logging',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.4.1',
    status: 'Ok',
    title: 'Event logging',
  },
  {
    asset_id: 171,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: 55,
    description:
      'The clocks of all relevant information processing systems within an organization or security domain shall be synchronised to a single reference time source.',
    docs: null,
    effective_risk: 'Ok',
    id: 55,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Operations Security / Clock Synchronisation',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.4.4',
    status: 'Medium',
    title: 'Clock Synchronisation',
  },
  {
    asset_id: 172,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: 56,
    description:
      'Procedures shall be implemented to control the installation of software on operational systems.',
    docs: null,
    effective_risk: 'Ok',
    id: 56,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Operations Security / Installation of software on operational systems',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.5.1',
    status: 'Medium',
    title: 'Installation of software on operational systems',
  },
  {
    asset_id: 173,
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    compliance: 'ISO 27001',
    compliance_id: 60,
    description:
      'Networks shall be managed and controlled to protect information in systems and applications.',
    docs: null,
    effective_risk: 'Ok',
    id: 60,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Communications Security / Network Controls',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.13.1.1',
    status: 'Medium',
    title: 'Network Controls',
  },
  {
    asset_id: 174,
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    compliance: 'ISO 27001',
    compliance_id: 61,
    description:
      'Security mechanisms, service levels and management requirements of all network services shall be identified and included in network services agreements, whether these services are provided in-house or outsourced.',
    docs: null,
    effective_risk: 'Ok',
    id: 61,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Communications Security / Security of Network Services',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.13.1.2',
    status: 'Ok',
    title: 'Security of Network Services',
  },
  {
    asset_id: 175,
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    compliance: 'ISO 27001',
    compliance_id: 62,
    description:
      'Groups of information services, users and information systems shall be segregated on networks.',
    docs: null,
    effective_risk: 'Ok',
    id: 62,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Communications Security / Segregation in Networks',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.13.1.3',
    status: 'Low',
    title: 'Segregation in Networks',
  },
  {
    asset_id: 176,
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    compliance: 'ISO 27001',
    compliance_id: 63,
    description:
      'Formal transfer policies, procedures and controls shall be in place to protect the transfer of information through the use of all types of communication facilities.',
    docs: null,
    effective_risk: 'Ok',
    id: 63,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Communications Security / Information transfer policies and procedures',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.13.2.1',
    status: 'High',
    title: 'Information transfer policies and procedures',
  },
  {
    asset_id: 177,
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    compliance: 'ISO 27001',
    compliance_id: 64,
    description:
      'Information involved in electronic messaging shall be appropriately protected.',
    docs: null,
    effective_risk: 'Ok',
    id: 64,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: 'ISO 27001 / Communications Security / Electronic messaging',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.13.2.3',
    status: 'High',
    title: 'Electronic messaging',
  },
  {
    asset_id: 178,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: 75,
    description:
      'Testing of security functionality shall be carried out during development.',
    docs: null,
    effective_risk: 'Ok',
    id: 75,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / System Acquisition, Development and Maintenance / System security testing',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.8',
    status: 'Ok',
    title: 'System security testing',
  },
  {
    asset_id: 179,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: 77,
    description:
      'Test data shall be selected carefully, protected and controlled.',
    docs: null,
    effective_risk: 'Ok',
    id: 77,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / System Acquisition, Development and Maintenance / Protection of test data',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.3.1',
    status: 'Ok',
    title: 'Protection of test data',
  },
  {
    asset_id: 180,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: 76,
    description:
      'Acceptance testing programs and related criteria shall be established for new information systems, upgrades and new versions.',
    docs: null,
    effective_risk: 'Ok',
    id: 76,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / System Acquisition, Development and Maintenance / System acceptance testing',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.9',
    status: 'Ok',
    title: 'System acceptance testing',
  },
  {
    asset_id: 181,
    chapter: 'Supplier Relationships',
    chapter_small: 'ISO Chapter A.15',
    compliance: 'ISO 27001',
    compliance_id: 78,
    description:
      'All relevant information security requirements shall be established and agreed with each supplier that may access, process, store, communicate, or provide IT infrastructure components for the organization’s information.',
    docs: null,
    effective_risk: 'Ok',
    id: 78,
    inneffective_risk: 'Medium',
    mitigation: null,
    name:
      'ISO 27001 / Supplier Relationships / Addressing security within supplier agreements',
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.15.1.2',
    status: 'Medium',
    title: 'Addressing security within supplier agreements',
  },
  {
    asset_id: null,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Media containing information shall be protected against unauthorized access, misuse or corruption during transportation.',
    docs: null,
    effective_risk: 'Ok',
    id: 17,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.3.3',
    status: null,
    title: 'Physical media transfer',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Information involved in application services passing over public networks shall be protected from fraudulent activity, contract dispute and unauthorized disclosure and modification.',
    docs: null,
    effective_risk: 'Ok',
    id: 66,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.1.2',
    status: null,
    title: 'Securing application services on public networks',
  },
  {
    asset_id: null,
    chapter: 'Information Security Aspects of Business Continuity Management',
    chapter_small: 'ISO Chapter A.17',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.',
    docs: null,
    effective_risk: 'Ok',
    id: 89,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.17.2.1',
    status: null,
    title: 'Availability of information processing facilities',
  },
  {
    asset_id: null,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Information about technical vulnerabilities of information systems being used shall be obtained in a timely fashion, the organization’s exposure to such vulnerabilities evaluated and appropriate measures taken to address the associated risk.',
    docs: null,
    effective_risk: 'Ok',
    id: 57,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.6.1',
    status: null,
    title: 'Management of technical vulnerabilities',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Modifications to software packages* shall be discouraged, limited to necessary changes and all changes shall be strictly controlled.  *Software package includes vendor-supplied and 3rd party software package',
    docs: null,
    effective_risk: 'Ok',
    id: 71,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.4',
    status: null,
    title: 'Restrictions on changes to software packages',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Principles for engineering secure systems shall be established, documented, maintained and applied to any information systems implementation efforts.',
    docs: null,
    effective_risk: 'Ok',
    id: 72,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.5',
    status: null,
    title: 'Secure system engineering principles',
  },
  {
    asset_id: null,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Changes to the organization, business processes, information processing facilities and systems that affect information security shall be controlled.',
    docs: null,
    effective_risk: 'Ok',
    id: 47,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.1.2',
    status: null,
    title: 'Change Management',
  },
  {
    asset_id: null,
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'A clear desk policy for papers and removable storage media and a clear screen policy for information processing facilities shall be adopted.',
    docs: null,
    effective_risk: 'Ok',
    id: 46,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.11.2.9',
    status: null,
    title: 'Clear desk and screen policy',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Organizations shall establish and appropriately protect secure development environments for system development and integration efforts that cover the entire system development lifecycle.',
    docs: null,
    effective_risk: 'Ok',
    id: 73,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.6',
    status: null,
    title: 'Secure development environment',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'The information security related requirements shall be included in the requirements for new information systems or enhancements to existing information systems.',
    docs: null,
    effective_risk: 'Ok',
    id: 65,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.1.1',
    status: null,
    title: 'Information security requirements analysis and specification',
  },
  {
    asset_id: null,
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Knowledge gained from analyzing and resolving information security incidents shall be used to reduce the likelihood or impact of future incidents.',
    docs: null,
    effective_risk: 'Ok',
    id: 85,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.16.1.6',
    status: null,
    title: 'Learning from information security incidents',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Rules for the development of software and systems shall be established and applied to developments within the organization.',
    docs: null,
    effective_risk: 'Ok',
    id: 68,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.1',
    status: null,
    title: 'Secure development policy',
  },
  {
    asset_id: null,
    chapter: 'Supplier Relationships',
    chapter_small: 'ISO Chapter A.15',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Organizations shall regularly monitor, review and audit supplier service delivery.',
    docs: null,
    effective_risk: 'Ok',
    id: 80,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.15.2.1',
    status: null,
    title: 'Monitoring and review of supplier services',
  },
  {
    asset_id: null,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'The use of resources shall be monitored, tuned and projections made of future capacity requirements to ensure the required system performance.',
    docs: null,
    effective_risk: 'Ok',
    id: 48,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.1.3',
    status: null,
    title: 'Capacity Management',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Information involved in application service transactions shall be protected to prevent incomplete transmission, mis-routing, unauthorized message alteration, unauthorized disclosure, unauthorized message duplication or replay.',
    docs: null,
    effective_risk: 'Ok',
    id: 67,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.1.3',
    status: null,
    title: 'Protecting application services transactions',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Changes to systems within the development lifecycle shall be controlled by the use of formal change control procedures.',
    docs: null,
    effective_risk: 'Ok',
    id: 69,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.2',
    status: null,
    title: 'System change control procedures',
  },
  {
    asset_id: null,
    chapter: 'Supplier Relationships',
    chapter_small: 'ISO Chapter A.15',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Agreements with suppliers shall include requirements to address the information security risks associated with information and communications technology services and product supply chain.',
    docs: null,
    effective_risk: 'Ok',
    id: 79,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.15.1.3',
    status: null,
    title: 'Information and communication technology supply chain',
  },
  {
    asset_id: null,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Audit requirements and activities involving verification of operational systems shall be carefully planned and agreed to minimise disruptions to business processes.',
    docs: null,
    effective_risk: 'Ok',
    id: 59,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.7.1',
    status: null,
    title: 'Information systems audit controls',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'The organization shall supervise and monitor the activity of outsourced system development.',
    docs: null,
    effective_risk: 'Ok',
    id: 74,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.7',
    status: null,
    title: 'Outsourced development',
  },
  {
    asset_id: null,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'System administrator and system operator activities shall be logged and the logs protected and regularly reviewed.',
    docs: null,
    effective_risk: 'Ok',
    id: 54,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.4.3',
    status: null,
    title: 'Administrator and Operator Logs',
  },
  {
    asset_id: null,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Logging facilities and log information shall be protected against tampering and unauthorized access.',
    docs: null,
    effective_risk: 'Ok',
    id: 53,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.4.2',
    status: null,
    title: 'Protection of log information',
  },
  {
    asset_id: null,
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Privacy and protection of personally identifiable information shall be ensured as required in relevant legislation and regulation where applicable.',
    docs: null,
    effective_risk: 'Ok',
    id: 92,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.18.1.4',
    status: null,
    title: 'Privacy and protection of personally identifiable information',
  },
  {
    asset_id: null,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Rules governing the installation of software by users shall be established and implemented.',
    docs: null,
    effective_risk: 'Ok',
    id: 58,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.6.2',
    status: null,
    title: 'Restrictions on software installation',
  },
  {
    asset_id: null,
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Development, testing, and operational environments shall be separated to reduce the risks of unauthorized access or changes to the operational environment.',
    docs: null,
    effective_risk: 'Ok',
    id: 49,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.12.1.4',
    status: null,
    title: 'Separation of development, testing and operational environments',
  },
  {
    asset_id: null,
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'When operating platforms are changed, business critical applications shall be reviewed and tested to ensure there is no adverse impact on organizational operations or security.',
    docs: null,
    effective_risk: 'Ok',
    id: 70,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.14.2.3',
    status: null,
    title: 'Technical review of applications after operating platform changes',
  },
  {
    asset_id: null,
    chapter: 'Information Security Aspects of Business Continuity Management',
    chapter_small: 'ISO Chapter A.17',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'The organization shall establish, document, implement and maintain processes, procedures and controls to ensure the required level of continuity for information security during an adverse situation.',
    docs: null,
    effective_risk: 'Ok',
    id: 87,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.17.1.2',
    status: null,
    title: 'Implementing information security continuity',
  },
  {
    asset_id: null,
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'Procedures for handling assets shall be developed and implemented in accordance with the information classification scheme adopted by the organization.',
    docs: null,
    effective_risk: 'Ok',
    id: 14,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.8.2.3',
    status: null,
    title: 'Handling of assets',
  },
  {
    asset_id: null,
    chapter: 'Information Security Aspects of Business Continuity Management',
    chapter_small: 'ISO Chapter A.17',
    compliance: 'ISO 27001',
    compliance_id: null,
    description:
      'The organization shall verify the established and implemented information security continuity controls at regular intervals in order to ensure that they are valid and effective during adverse situations.',
    docs: null,
    effective_risk: 'Ok',
    id: 88,
    inneffective_risk: 'Medium',
    mitigation: null,
    name: null,
    non_existant_risk: 'High',
    partially_effective_risk: 'Low',
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
    section: 'A.17.1.3',
    status: null,
    title: 'Verify, review and evaluate information security continuity',
  },
]
