/**
 * @typedef {{
 *  id: number,
 *  compliance: string
 *  chapter: string,
 *  chapter_small: string,
 *  title: string,
 *  section: string,
 *  description: string,
 *  non_existant_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  inneffective_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  partially_effective_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  effective_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  docs: string,
 *  asset_id: number,
 *  name: string,
 *  compliance_id: number,
 *  status: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  mitigation: string,
 *  residual_risk: 'Critical' | 'High' | 'Medium' | 'Low' | 'Ok' | null,
 *  response: {text: string, value: string}[]
 * }} compliance
 */

/**
 * @type {compliance[]}
 */
export default [
  {
    id: 20,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'User access provisioning',
    section: 'A.9.2.2',
    description:
      'A formal user access provisioning process shall be implemented to assign or revoke user access rights to systems and services.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 92,
    name: 'ISO 27001 / Access Control / User access provisioning',
    compliance_id: 20,
    status: 'High',
    mitigation: 'No user',
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 25,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Information access restriction',
    section: 'A.9.4.1',
    description:
      'Access to information and application system functions shall be restricted in accordance with the access control policy.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 115,
    name: 'ISO 27001 / Access Control / Information access restriction',
    compliance_id: 25,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 26,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Secure log-on procedures',
    section: 'A.9.4.2',
    description:
      'Where required by the access control policy, access to systems and applications shall be controlled by a secure log-on procedure.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 116,
    name: 'ISO 27001 / Access Control / Secure log-on procedures',
    compliance_id: 26,
    status: 'High',
    mitigation: null,
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 27,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Password management system',
    section: 'A.9.4.3',
    description:
      'Password management systems shall be interactive and shall ensure quality passwords.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 117,
    name: 'ISO 27001 / Access Control / Password management system',
    compliance_id: 27,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 18,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Access to networks and network services',
    section: 'A.9.1.2',
    description:
      'Users shall only be provided with access to the network and network services that they have been specifically authorized to use.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 118,
    name:
      'ISO 27001 / Access Control / Access to networks and network services',
    compliance_id: 18,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 21,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Management of privileged access rights',
    section: 'A.9.2.3',
    description:
      'The allocation and use of privileged access rights shall be restricted and controlled.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 119,
    name: 'ISO 27001 / Access Control / Management of privileged access rights',
    compliance_id: 21,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 19,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'User registration and de-registration',
    section: 'A.9.2.1',
    description:
      'A formal user registration and de-registration process shall be implemented to enable assignment of access rights.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 120,
    name: 'ISO 27001 / Access Control / User registration and de-registration',
    compliance_id: 19,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 24,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Removal or adjustment of access rights',
    section: 'A.9.2.6',
    description:
      'The access rights of all employees and external party users to information and information processing facilities shall be removed upon termination of their employment, contract or agreement, or adjusted upon change.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 121,
    name: 'ISO 27001 / Access Control / Removal or adjustment of access rights',
    compliance_id: 24,
    status: 'High',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 28,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Use of privileged utility programs',
    section: 'A.9.4.4',
    description:
      'The use of utility programs that might be capable of overriding system and application controls shall be restricted and tightly controlled.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 122,
    name: 'ISO 27001 / Access Control / Use of privileged utility programs',
    compliance_id: 28,
    status: 'High',
    mitigation: null,
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 29,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Access control to program source code',
    section: 'A.9.4.5',
    description: 'Access to program source code shall be restricted.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 123,
    name: 'ISO 27001 / Access Control / Access control to program source code',
    compliance_id: 29,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 23,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Review of user access rights',
    section: 'A.9.2.5',
    description:
      'Asset owners shall review users’ access rights at regular intervals.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 124,
    name: 'ISO 27001 / Access Control / Review of user access rights',
    compliance_id: 23,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 22,
    compliance: 'ISO 27001',
    chapter: 'Access Control',
    chapter_small: 'ISO Chapter A.9',
    title: 'Management of secret authentication information of users',
    section: 'A.9.2.4',
    description:
      'The allocation of secret authentication information shall be controlled through a formal management process.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 125,
    name:
      'ISO 27001 / Access Control / Management of secret authentication information of users',
    compliance_id: 22,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 82,
    compliance: 'ISO 27001',
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    title: 'Reporting information security weaknesses',
    section: 'A.16.1.3',
    description:
      'Employees and contractors using the organization’s information systems and services shall be required to note and report any observed or suspected information security weaknesses in systems or services.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 126,
    name:
      'ISO 27001 / Information Security Incident Management / Reporting information security weaknesses',
    compliance_id: 82,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 83,
    compliance: 'ISO 27001',
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    title: 'Assessment of and decision on information security events',
    section: 'A.16.1.4',
    description:
      'Information security events shall be assessed and it shall be decided if they are to be classified as information security incidents.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 127,
    name:
      'ISO 27001 / Information Security Incident Management / Assessment of and decision on information security events',
    compliance_id: 83,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 81,
    compliance: 'ISO 27001',
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    title: 'Reporting information security events',
    section: 'A.16.1.2',
    description:
      'Information security events shall be reported through appropriate management channels as quickly as possible.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 128,
    name:
      'ISO 27001 / Information Security Incident Management / Reporting information security events',
    compliance_id: 81,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 84,
    compliance: 'ISO 27001',
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    title: 'Response to information security incidents',
    section: 'A.16.1.5',
    description:
      'Information security incidents shall be responded to in accordance with the documented procedures.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 129,
    name:
      'ISO 27001 / Information Security Incident Management / Response to information security incidents',
    compliance_id: 84,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 86,
    compliance: 'ISO 27001',
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    title: 'Collection of evidence',
    section: 'A.16.1.7',
    description:
      'The organization shall define and apply procedures for the identification, collection, acquisition and preservation of information, which can serve as evidence.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 130,
    name:
      'ISO 27001 / Information Security Incident Management / Collection of evidence',
    compliance_id: 86,
    status: 'High',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 93,
    compliance: 'ISO 27001',
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    title: 'Regulation of cryptographic controls',
    section: 'A.18.1.5',
    description:
      'Cryptographic controls shall be used in compliance with all relevant agreements, legislation and regulations.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 131,
    name: 'ISO 27001 / Compliance / Regulation of cryptographic controls',
    compliance_id: 93,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 91,
    compliance: 'ISO 27001',
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    title: 'Protection of records',
    section: 'A.18.1.3',
    description:
      'Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release, in accordance with legislator, regulatory, contractual and business requirements.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 132,
    name: 'ISO 27001 / Compliance / Protection of records',
    compliance_id: 91,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 96,
    compliance: 'ISO 27001',
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    title: 'Technical compliance review',
    section: 'A.18.2.3',
    description:
      'Information systems shall be regularly reviewed for compliance with the organization’s information security policies and standards.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 133,
    name: 'ISO 27001 / Compliance / Technical compliance review',
    compliance_id: 96,
    status: 'High',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 94,
    compliance: 'ISO 27001',
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    title: 'Independent review of information security',
    section: 'A.18.2.1',
    description:
      'The organization’s approach to managing information security and its implementation (i.e. control objectives, controls, policies, processes and procedures for information security) shall be reviewed independently at planned intervals or when significant changes occur.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 134,
    name: 'ISO 27001 / Compliance / Independent review of information security',
    compliance_id: 94,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 95,
    compliance: 'ISO 27001',
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    title: 'Compliance with security policies and standards',
    section: 'A.18.2.2',
    description:
      'Managers shall regularly review the compliance of information processing and procedures within their area of responsibility with the appropriate security policies, standards and any other security requirements.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 135,
    name:
      'ISO 27001 / Compliance / Compliance with security policies and standards',
    compliance_id: 95,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 90,
    compliance: 'ISO 27001',
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    title: 'Intellectual property rights',
    section: 'A.18.1.2',
    description:
      'Appropriate procedures shall be implemented to ensure compliance with legislative, regulatory and contractual requirements related to intellectual property rights and use of proprietary software products.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 136,
    name: 'ISO 27001 / Compliance / Intellectual property rights',
    compliance_id: 90,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 1,
    compliance: 'ISO 27001',
    chapter: 'Organization of Information Security',
    chapter_small: 'ISO Chapter A.6',
    title: 'Segregation of duties',
    section: 'A.6.1.2',
    description:
      'Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of the organization’s assets.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 137,
    name:
      'ISO 27001 / Organization of Information Security / Segregation of duties',
    compliance_id: 1,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 2,
    compliance: 'ISO 27001',
    chapter: 'Organization of Information Security',
    chapter_small: 'ISO Chapter A.6',
    title: 'Infromation security in project management',
    section: 'A.6.1.5',
    description:
      'Information security should be addressed in project management, regardless of the type of the project',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 138,
    name:
      'ISO 27001 / Organization of Information Security / Infromation security in project management',
    compliance_id: 2,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 3,
    compliance: 'ISO 27001',
    chapter: 'Organization of Information Security',
    chapter_small: 'ISO Chapter A.6',
    title: 'Mobile Device Policy',
    section: 'A.6.2.1',
    description:
      'A policy and supporting security measures shall be adopted to manage the risks introduced by using mobile devices.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 139,
    name:
      'ISO 27001 / Organization of Information Security / Mobile Device Policy',
    compliance_id: 3,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 4,
    compliance: 'ISO 27001',
    chapter: 'Human Resources Security',
    chapter_small: 'ISO Chapter A.7',
    title: 'Screening',
    section: 'A.7.1.1',
    description:
      'Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations and ethics and shall be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 140,
    name: 'ISO 27001 / Human Resources Security / Screening',
    compliance_id: 4,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 5,
    compliance: 'ISO 27001',
    chapter: 'Human Resources Security',
    chapter_small: 'ISO Chapter A.7',
    title: 'Management responsibilities',
    section: 'A.7.2.1',
    description:
      'Management shall require all employees and contractors to apply information security in accordance with the established policies and procedures of the organization.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 141,
    name: 'ISO 27001 / Human Resources Security / Management responsibilities',
    compliance_id: 5,
    status: 'High',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 6,
    compliance: 'ISO 27001',
    chapter: 'Human Resources Security',
    chapter_small: 'ISO Chapter A.7',
    title: 'Information security awareness, education and training',
    section: 'A.7.2.2',
    description:
      'All employees of the organization and, where relevant, contractors shall receive appropriate awareness education and training and regular updates in organizational policies and procedures, as relevant for their job function.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 142,
    name:
      'ISO 27001 / Human Resources Security / Information security awareness, education and training',
    compliance_id: 6,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 7,
    compliance: 'ISO 27001',
    chapter: 'Human Resources Security',
    chapter_small: 'ISO Chapter A.7',
    title: 'Termination or change of employment responsibilities',
    section: 'A.7.3.1',
    description:
      'Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, communicated to the employee or contractor and enforced.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 143,
    name:
      'ISO 27001 / Human Resources Security / Termination or change of employment responsibilities',
    compliance_id: 7,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 8,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Inventory of Assets',
    section: 'A.8.1.1',
    description:
      'Assets associated with information and information processing facilities shall be identified and an inventory of these assets shall be drawn up and maintained.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 144,
    name: 'ISO 27001 / Asset Management / Inventory of Assets',
    compliance_id: 8,
    status: 'Ok',
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 9,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Ownership of Assets',
    section: 'A.8.1.2',
    description: 'Assets maintained in the inventory shall be owned.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 145,
    name: 'ISO 27001 / Asset Management / Ownership of Assets',
    compliance_id: 9,
    status: 'Ok',
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 10,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Acceptable use of Assets',
    section: 'A.8.1.3',
    description:
      'Rules for the acceptable use of information and of assets associated with information and information processing facilities shall be identified, documented and implemented.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 146,
    name: 'ISO 27001 / Asset Management / Acceptable use of Assets',
    compliance_id: 10,
    status: 'Ok',
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 11,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Return of Assets',
    section: 'A.8.1.4',
    description:
      'All employees and external party users shall return all of the organizational assets in their possession upon termination of their employment, contract or agreement.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 147,
    name: 'ISO 27001 / Asset Management / Return of Assets',
    compliance_id: 11,
    status: 'Ok',
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 12,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Classification of information',
    section: 'A.8.2.1',
    description:
      'Information shall be classified in terms of legal requirements, value, criticality and sensitivity to unauthorized disclosure or modification.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 148,
    name: 'ISO 27001 / Asset Management / Classification of information',
    compliance_id: 12,
    status: 'High',
    mitigation: null,
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 13,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Labelling of information',
    section: 'A.8.2.2',
    description:
      'An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 149,
    name: 'ISO 27001 / Asset Management / Labelling of information',
    compliance_id: 13,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 15,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Management of removable media',
    section: 'A.8.3.1',
    description:
      'Procedures shall be implemented for the management of removable media* in accordance with the classification scheme adopted by the organization.  *any type of storage device that can be removed from a computer while the system is running (e.g. DVD, BR, USB drives…)',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 150,
    name: 'ISO 27001 / Asset Management / Management of removable media',
    compliance_id: 15,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 16,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Disposal of media',
    section: 'A.8.3.2',
    description:
      'Media shall be disposed of securely when no longer required, using formal procedures.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 151,
    name: 'ISO 27001 / Asset Management / Disposal of media',
    compliance_id: 16,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 30,
    compliance: 'ISO 27001',
    chapter: 'Cryptography',
    chapter_small: 'ISO Chapter A.10',
    title: 'Policy on the use of cryptographic controls',
    section: 'A.10.1.1',
    description:
      'A policy on the use of cryptographic controls for protection of information shall be developed and implemented.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 152,
    name:
      'ISO 27001 / Cryptography / Policy on the use of cryptographic controls',
    compliance_id: 30,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 31,
    compliance: 'ISO 27001',
    chapter: 'Cryptography',
    chapter_small: 'ISO Chapter A.10',
    title: 'Key management',
    section: 'A.10.1.2',
    description:
      'A policy on the use, protection and lifetime of cryptographic keys shall be developed and implemented through their whole lifecycle.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 153,
    name: 'ISO 27001 / Cryptography / Key management',
    compliance_id: 31,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 32,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Physical security perimeter',
    section: 'A.11.1.1',
    description:
      'Security perimeters shall be defined and used to protect areas that contain either sensitive or critical information and information processing facilities.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 154,
    name:
      'ISO 27001 / Physical and Environmental Security / Physical security perimeter',
    compliance_id: 32,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 33,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Physical entry controls',
    section: 'A.11.1.2',
    description:
      'Secure areas shall be protected by appropriate entry controls to ensure that only authorized personnel are allowed access.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 155,
    name:
      'ISO 27001 / Physical and Environmental Security / Physical entry controls',
    compliance_id: 33,
    status: 'High',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 34,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Securing offices rooms and facilities',
    section: 'A.11.1.3',
    description:
      'Physical security for offices, rooms and facilities shall be designed and applied.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 156,
    name:
      'ISO 27001 / Physical and Environmental Security / Securing offices rooms and facilities',
    compliance_id: 34,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 35,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Protecting against external and environmental threats',
    section: 'A.11.1.4',
    description:
      'Physical protection against natural disasters, malicious attack or accidents shall be designed and applied.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 157,
    name:
      'ISO 27001 / Physical and Environmental Security / Protecting against external and environmental threats',
    compliance_id: 35,
    status: 'High',
    mitigation: null,
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 36,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Working in secure areas',
    section: 'A.11.1.5',
    description:
      'Procedures for working in secure areas shall be designed and applied.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 158,
    name:
      'ISO 27001 / Physical and Environmental Security / Working in secure areas',
    compliance_id: 36,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 37,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Delivery and loading areas',
    section: 'A.11.1.6',
    description:
      'Access points such as delivery and loading areas and other points where unauthorized persons could enter the premises shall be controlled and, if possible, isolated from information processing facilities to avoid unauthorized access.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 159,
    name:
      'ISO 27001 / Physical and Environmental Security / Delivery and loading areas',
    compliance_id: 37,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 38,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Equipment siting and protection',
    section: 'A.11.2.1',
    description:
      'Equipment shall be sited and protected to reduce the risks from environmental threats and hazards, and opportunities for unauthorized access.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 160,
    name:
      'ISO 27001 / Physical and Environmental Security / Equipment siting and protection',
    compliance_id: 38,
    status: 'High',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 39,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Supporting utilities',
    section: 'A.11.2.2',
    description:
      'Equipment shall be protected from power failures and other disruptions caused by failures in supporting utilities.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 161,
    name:
      'ISO 27001 / Physical and Environmental Security / Supporting utilities',
    compliance_id: 39,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 40,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Cabling security',
    section: 'A.11.2.3',
    description:
      'Power and telecommunications cabling carrying data or supporting information services shall be protected from interception, interference or damage.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 162,
    name: 'ISO 27001 / Physical and Environmental Security / Cabling security',
    compliance_id: 40,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 41,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Equipment maintenance',
    section: 'A.11.2.4',
    description:
      'Equipment shall be correctly maintained to ensure its continued availability and integrity.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 163,
    name:
      'ISO 27001 / Physical and Environmental Security / Equipment maintenance',
    compliance_id: 41,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 42,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Removal of assets',
    section: 'A.11.2.5',
    description:
      'Equipment, information or software shall not be taken off-site without prior authorization.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 164,
    name: 'ISO 27001 / Physical and Environmental Security / Removal of assets',
    compliance_id: 42,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 43,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Security of equipment and assets off premises',
    section: 'A.11.2.6',
    description:
      "Security shall be applied to off-site assets taking into account the different risks of working outside the organization's premises",
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 165,
    name:
      'ISO 27001 / Physical and Environmental Security / Security of equipment and assets off premises',
    compliance_id: 43,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 44,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Secure Disposal or reuse of equipment',
    section: 'A.11.2.7',
    description:
      'All items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 166,
    name:
      'ISO 27001 / Physical and Environmental Security / Secure Disposal or reuse of equipment',
    compliance_id: 44,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 45,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Unattended user equipment',
    section: 'A.11.2.8',
    description:
      'Users shall ensure that unattended equipment has appropriate protection.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 167,
    name:
      'ISO 27001 / Physical and Environmental Security / Unattended user equipment',
    compliance_id: 45,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 50,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Controls against Malware',
    section: 'A.12.2.1',
    description:
      'Detection, prevention and recovery controls to protect against malware shall be implemented.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 168,
    name: 'ISO 27001 / Operations Security / Controls against Malware',
    compliance_id: 50,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 51,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Information Backup',
    section: 'A.12.3.1',
    description:
      'Backup copies of information, software and system images shall be taken and tested regularly in accordance with an agreed backup policy.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 169,
    name: 'ISO 27001 / Operations Security / Information Backup',
    compliance_id: 51,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 52,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Event logging',
    section: 'A.12.4.1',
    description:
      'Event logs recording user activities, exceptions, faults and information security events shall be produced, kept and regularly reviewed.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 170,
    name: 'ISO 27001 / Operations Security / Event logging',
    compliance_id: 52,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 55,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Clock Synchronisation',
    section: 'A.12.4.4',
    description:
      'The clocks of all relevant information processing systems within an organization or security domain shall be synchronised to a single reference time source.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 171,
    name: 'ISO 27001 / Operations Security / Clock Synchronisation',
    compliance_id: 55,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 56,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Installation of software on operational systems',
    section: 'A.12.5.1',
    description:
      'Procedures shall be implemented to control the installation of software on operational systems.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 172,
    name:
      'ISO 27001 / Operations Security / Installation of software on operational systems',
    compliance_id: 56,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'Low',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 60,
    compliance: 'ISO 27001',
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    title: 'Network Controls',
    section: 'A.13.1.1',
    description:
      'Networks shall be managed and controlled to protect information in systems and applications.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 173,
    name: 'ISO 27001 / Communications Security / Network Controls',
    compliance_id: 60,
    status: 'Medium',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 61,
    compliance: 'ISO 27001',
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    title: 'Security of Network Services',
    section: 'A.13.1.2',
    description:
      'Security mechanisms, service levels and management requirements of all network services shall be identified and included in network services agreements, whether these services are provided in-house or outsourced.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 174,
    name: 'ISO 27001 / Communications Security / Security of Network Services',
    compliance_id: 61,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 62,
    compliance: 'ISO 27001',
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    title: 'Segregation in Networks',
    section: 'A.13.1.3',
    description:
      'Groups of information services, users and information systems shall be segregated on networks.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 175,
    name: 'ISO 27001 / Communications Security / Segregation in Networks',
    compliance_id: 62,
    status: 'Low',
    mitigation: null,
    residual_risk: 'Medium',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 63,
    compliance: 'ISO 27001',
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    title: 'Information transfer policies and procedures',
    section: 'A.13.2.1',
    description:
      'Formal transfer policies, procedures and controls shall be in place to protect the transfer of information through the use of all types of communication facilities.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 176,
    name:
      'ISO 27001 / Communications Security / Information transfer policies and procedures',
    compliance_id: 63,
    status: 'High',
    mitigation: null,
    residual_risk: 'Critical',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 64,
    compliance: 'ISO 27001',
    chapter: 'Communications Security',
    chapter_small: 'ISO Chapter A.13',
    title: 'Electronic messaging',
    section: 'A.13.2.3',
    description:
      'Information involved in electronic messaging shall be appropriately protected.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 177,
    name: 'ISO 27001 / Communications Security / Electronic messaging',
    compliance_id: 64,
    status: 'High',
    mitigation: null,
    residual_risk: 'High',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 75,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'System security testing',
    section: 'A.14.2.8',
    description:
      'Testing of security functionality shall be carried out during development.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 178,
    name:
      'ISO 27001 / System Acquisition, Development and Maintenance / System security testing',
    compliance_id: 75,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 77,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Protection of test data',
    section: 'A.14.3.1',
    description:
      'Test data shall be selected carefully, protected and controlled.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 179,
    name:
      'ISO 27001 / System Acquisition, Development and Maintenance / Protection of test data',
    compliance_id: 77,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 76,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'System acceptance testing',
    section: 'A.14.2.9',
    description:
      'Acceptance testing programs and related criteria shall be established for new information systems, upgrades and new versions.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 180,
    name:
      'ISO 27001 / System Acquisition, Development and Maintenance / System acceptance testing',
    compliance_id: 76,
    status: 'Ok',
    mitigation: null,
    residual_risk: 'Ok',
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 78,
    compliance: 'ISO 27001',
    chapter: 'Supplier Relationships',
    chapter_small: 'ISO Chapter A.15',
    title: 'Addressing security within supplier agreements',
    section: 'A.15.1.2',
    description:
      'All relevant information security requirements shall be established and agreed with each supplier that may access, process, store, communicate, or provide IT infrastructure components for the organization’s information.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: 181,
    name:
      'ISO 27001 / Supplier Relationships / Addressing security within supplier agreements',
    compliance_id: 78,
    status: 'Medium',
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 17,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Physical media transfer',
    section: 'A.8.3.3',
    description:
      'Media containing information shall be protected against unauthorized access, misuse or corruption during transportation.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 66,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Securing application services on public networks',
    section: 'A.14.1.2',
    description:
      'Information involved in application services passing over public networks shall be protected from fraudulent activity, contract dispute and unauthorized disclosure and modification.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 89,
    compliance: 'ISO 27001',
    chapter: 'Information Security Aspects of Business Continuity Management',
    chapter_small: 'ISO Chapter A.17',
    title: 'Availability of information processing facilities',
    section: 'A.17.2.1',
    description:
      'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 57,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Management of technical vulnerabilities',
    section: 'A.12.6.1',
    description:
      'Information about technical vulnerabilities of information systems being used shall be obtained in a timely fashion, the organization’s exposure to such vulnerabilities evaluated and appropriate measures taken to address the associated risk.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 71,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Restrictions on changes to software packages',
    section: 'A.14.2.4',
    description:
      'Modifications to software packages* shall be discouraged, limited to necessary changes and all changes shall be strictly controlled.  *Software package includes vendor-supplied and 3rd party software package',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 72,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Secure system engineering principles',
    section: 'A.14.2.5',
    description:
      'Principles for engineering secure systems shall be established, documented, maintained and applied to any information systems implementation efforts.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 47,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Change Management',
    section: 'A.12.1.2',
    description:
      'Changes to the organization, business processes, information processing facilities and systems that affect information security shall be controlled.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 46,
    compliance: 'ISO 27001',
    chapter: 'Physical and Environmental Security',
    chapter_small: 'ISO Chapter A.11',
    title: 'Clear desk and screen policy',
    section: 'A.11.2.9',
    description:
      'A clear desk policy for papers and removable storage media and a clear screen policy for information processing facilities shall be adopted.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 73,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Secure development environment',
    section: 'A.14.2.6',
    description:
      'Organizations shall establish and appropriately protect secure development environments for system development and integration efforts that cover the entire system development lifecycle.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 65,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Information security requirements analysis and specification',
    section: 'A.14.1.1',
    description:
      'The information security related requirements shall be included in the requirements for new information systems or enhancements to existing information systems.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 85,
    compliance: 'ISO 27001',
    chapter: 'Information Security Incident Management',
    chapter_small: 'ISO Chapter A.16',
    title: 'Learning from information security incidents',
    section: 'A.16.1.6',
    description:
      'Knowledge gained from analyzing and resolving information security incidents shall be used to reduce the likelihood or impact of future incidents.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 68,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Secure development policy',
    section: 'A.14.2.1',
    description:
      'Rules for the development of software and systems shall be established and applied to developments within the organization.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 80,
    compliance: 'ISO 27001',
    chapter: 'Supplier Relationships',
    chapter_small: 'ISO Chapter A.15',
    title: 'Monitoring and review of supplier services',
    section: 'A.15.2.1',
    description:
      'Organizations shall regularly monitor, review and audit supplier service delivery.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 48,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Capacity Management',
    section: 'A.12.1.3',
    description:
      'The use of resources shall be monitored, tuned and projections made of future capacity requirements to ensure the required system performance.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 67,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Protecting application services transactions',
    section: 'A.14.1.3',
    description:
      'Information involved in application service transactions shall be protected to prevent incomplete transmission, mis-routing, unauthorized message alteration, unauthorized disclosure, unauthorized message duplication or replay.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 69,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'System change control procedures',
    section: 'A.14.2.2',
    description:
      'Changes to systems within the development lifecycle shall be controlled by the use of formal change control procedures.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 79,
    compliance: 'ISO 27001',
    chapter: 'Supplier Relationships',
    chapter_small: 'ISO Chapter A.15',
    title: 'Information and communication technology supply chain',
    section: 'A.15.1.3',
    description:
      'Agreements with suppliers shall include requirements to address the information security risks associated with information and communications technology services and product supply chain.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 59,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Information systems audit controls',
    section: 'A.12.7.1',
    description:
      'Audit requirements and activities involving verification of operational systems shall be carefully planned and agreed to minimise disruptions to business processes.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 74,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Outsourced development',
    section: 'A.14.2.7',
    description:
      'The organization shall supervise and monitor the activity of outsourced system development.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 54,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Administrator and Operator Logs',
    section: 'A.12.4.3',
    description:
      'System administrator and system operator activities shall be logged and the logs protected and regularly reviewed.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 53,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Protection of log information',
    section: 'A.12.4.2',
    description:
      'Logging facilities and log information shall be protected against tampering and unauthorized access.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 92,
    compliance: 'ISO 27001',
    chapter: 'Compliance',
    chapter_small: 'ISO Chapter A.18',
    title: 'Privacy and protection of personally identifiable information',
    section: 'A.18.1.4',
    description:
      'Privacy and protection of personally identifiable information shall be ensured as required in relevant legislation and regulation where applicable.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 58,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Restrictions on software installation',
    section: 'A.12.6.2',
    description:
      'Rules governing the installation of software by users shall be established and implemented.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 49,
    compliance: 'ISO 27001',
    chapter: 'Operations Security',
    chapter_small: 'ISO Chapter A.12',
    title: 'Separation of development, testing and operational environments',
    section: 'A.12.1.4',
    description:
      'Development, testing, and operational environments shall be separated to reduce the risks of unauthorized access or changes to the operational environment.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 70,
    compliance: 'ISO 27001',
    chapter: 'System Acquisition, Development and Maintenance',
    chapter_small: 'ISO Chapter A.14',
    title: 'Technical review of applications after operating platform changes',
    section: 'A.14.2.3',
    description:
      'When operating platforms are changed, business critical applications shall be reviewed and tested to ensure there is no adverse impact on organizational operations or security.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 87,
    compliance: 'ISO 27001',
    chapter: 'Information Security Aspects of Business Continuity Management',
    chapter_small: 'ISO Chapter A.17',
    title: 'Implementing information security continuity',
    section: 'A.17.1.2',
    description:
      'The organization shall establish, document, implement and maintain processes, procedures and controls to ensure the required level of continuity for information security during an adverse situation.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 14,
    compliance: 'ISO 27001',
    chapter: 'Asset Management',
    chapter_small: 'ISO Chapter A.8',
    title: 'Handling of assets',
    section: 'A.8.2.3',
    description:
      'Procedures for handling assets shall be developed and implemented in accordance with the information classification scheme adopted by the organization.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
  {
    id: 88,
    compliance: 'ISO 27001',
    chapter: 'Information Security Aspects of Business Continuity Management',
    chapter_small: 'ISO Chapter A.17',
    title: 'Verify, review and evaluate information security continuity',
    section: 'A.17.1.3',
    description:
      'The organization shall verify the established and implemented information security continuity controls at regular intervals in order to ensure that they are valid and effective during adverse situations.',
    non_existant_risk: 'High',
    inneffective_risk: 'Medium',
    partially_effective_risk: 'Low',
    effective_risk: 'Ok',
    docs: null,
    asset_id: null,
    name: null,
    compliance_id: null,
    status: null,
    mitigation: null,
    residual_risk: null,
    response: [
      {
        text: 'Non Existant',
        value: 'High',
      },
      {
        text: 'Inneffective',
        value: 'Medium',
      },
      {
        text: 'Partially Effective',
        value: 'Low',
      },
      {
        text: 'Effective',
        value: 'Ok',
      },
    ],
  },
]
