const SCANS = [
  {
    cdate: '2022-06-01T13:40:51.691Z',
    fdate: null,
    id: 13,
    name: 'dazazd',
    probe: null,
    sdate: null,
    status: 'New',
    v_scan_asset_details: [
      {
        asset_id: 61,
        hostname: null,
        ip_address: ['10.256.1.5', '10.255.1.5'],
        language: null,
        mail: null,
        name: 'Bob-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 62,
        hostname: null,
        ip_address: ['10.256.1.256'],
        language: null,
        mail: null,
        name: 'Clara-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 53,
        hostname: null,
        ip_address: ['10.256.0.2'],
        language: null,
        mail: null,
        name: 'CMPAD02',
        os: 'windows',
        url: null,
      },
    ],
    v_scan_severity_count: [
      { critical: 15, high: 47, info: 62, low: 34, medium: 113 },
    ],
  },
  {
    cdate: '2022-05-01T13:40:51.691Z',
    fdate: null,
    id: 12,
    name: 'adzazd',
    probe: { name: 'RedProbe' },
    sdate: null,
    status: 'New',
    v_scan_asset_details: [
      {
        asset_id: 61,
        hostname: null,
        ip_address: ['10.256.1.5', '10.255.1.5'],
        language: null,
        mail: null,
        name: 'Bob-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 62,
        hostname: null,
        ip_address: ['10.256.1.256'],
        language: null,
        mail: null,
        name: 'Clara-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 53,
        hostname: null,
        ip_address: ['10.256.0.2'],
        language: null,
        mail: null,
        name: 'CMPAD02',
        os: 'windows',
        url: null,
      },
    ],
    v_scan_severity_count: [
      { critical: 15, high: 47, info: 62, low: 34, medium: 113 },
    ],
  },
  {
    cdate: '2022-04-01T13:56:30.728Z',
    fdate: null,
    id: 11,
    name: 'adzzad',
    probe: { name: 'RedProbe' },
    sdate: null,
    status: 'New',
    v_scan_asset_details: [
      {
        asset_id: 61,
        hostname: null,
        ip_address: ['10.256.1.5', '10.255.1.5'],
        language: null,
        mail: null,
        name: 'Bob-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 62,
        hostname: null,
        ip_address: ['10.256.1.256'],
        language: null,
        mail: null,
        name: 'Clara-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 53,
        hostname: null,
        ip_address: ['10.256.0.2'],
        language: null,
        mail: null,
        name: 'CMPAD02',
        os: 'windows',
        url: null,
      },
    ],
    v_scan_severity_count: [
      { critical: 15, high: 47, info: 62, low: 34, medium: 113 },
    ],
  },
  {
    cdate: null,
    fdate: null,
    id: 10,
    name: 'adzazd',
    probe: null,
    sdate: null,
    status: 'New',
    v_scan_asset_details: [],
    v_scan_severity_count: [],
  },
  {
    cdate: null,
    fdate: null,
    id: 9,
    name: 'sdq',
    probe: { name: 'GreenProbe' },
    sdate: null,
    status: 'New',
    v_scan_asset_details: [
      {
        asset_id: 61,
        hostname: null,
        ip_address: ['10.256.1.5', '10.255.1.5'],
        language: null,
        mail: null,
        name: 'Bob-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 62,
        hostname: null,
        ip_address: ['10.256.1.256'],
        language: null,
        mail: null,
        name: 'Clara-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 53,
        hostname: null,
        ip_address: ['10.256.0.2'],
        language: null,
        mail: null,
        name: 'CMPAD02',
        os: 'windows',
        url: null,
      },
    ],
    v_scan_severity_count: [
      { critical: 15, high: 47, info: 62, low: 34, medium: 113 },
    ],
  },
  {
    cdate: null,
    fdate: null,
    id: 8,
    name: 'fez',
    probe: { name: 'RedProbe' },
    sdate: null,
    status: 'New',
    v_scan_asset_details: [
      {
        asset_id: 61,
        hostname: null,
        ip_address: ['10.256.1.5', '10.255.1.5'],
        language: null,
        mail: null,
        name: 'Bob-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 62,
        hostname: null,
        ip_address: ['10.256.1.256'],
        language: null,
        mail: null,
        name: 'Clara-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 53,
        hostname: null,
        ip_address: ['10.256.0.2'],
        language: null,
        mail: null,
        name: 'CMPAD02',
        os: 'windows',
        url: null,
      },
    ],
    v_scan_severity_count: [],
  },
  {
    cdate: null,
    fdate: null,
    id: 7,
    name: 'test',
    probe: null,
    sdate: null,
    status: 'New',
    v_scan_asset_details: [],
    v_scan_severity_count: [],
  },
  {
    cdate: null,
    fdate: null,
    id: 6,
    name: 'phshingscan2',
    probe: null,
    sdate: null,
    status: 'New',
    v_scan_asset_details: [],
    v_scan_severity_count: [],
  },
  {
    cdate: null,
    fdate: null,
    id: 5,
    name: 'phishing scan',
    probe: null,
    sdate: null,
    status: 'New',
    v_scan_asset_details: [],
    v_scan_severity_count: [],
  },
  {
    cdate: null,
    fdate: null,
    id: 2,
    name: 'test',
    probe: null,
    sdate: null,
    status: 'New',
    v_scan_asset_details: [
      {
        asset_id: 61,
        hostname: null,
        ip_address: ['10.256.1.5', '10.255.1.5'],
        language: null,
        mail: null,
        name: 'Bob-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 62,
        hostname: null,
        ip_address: ['10.256.1.256'],
        language: null,
        mail: null,
        name: 'Clara-pc',
        os: 'Windows 10 - computer',
        url: null,
      },
      {
        asset_id: 53,
        hostname: null,
        ip_address: ['10.256.0.2'],
        language: null,
        mail: null,
        name: 'CMPAD02',
        os: 'windows',
        url: null,
      },
    ],
    v_scan_severity_count: [
      { critical: 15, high: 47, info: 62, low: 34, medium: 113 },
    ],
  },
]

export default SCANS

export function generateScans(size = 10) {
  const returnSize = Math.min(size, SCANS.length)
  return SCANS.slice(0, returnSize)
}

export const probe = {
  address: null,
  cdate: '2021-11-24T04:42:02.178Z',
  company_id: 1,
  exit_ip: null,
  gw: null,
  id: 2,
  info: null,
  mac: null,
  mask: null,
  name: 'ServerProbe',
  probe_type: 'SERVER',
  status: 'Down',
  store_id: null,
  url: null,
}
export function createScanContent(howManyType: any) {
  const typeBasedOnArg = []
  for (let i = 0; i < howManyType; i++)
    typeBasedOnArg.push(`test${i}`)

  return {
    endTime: '03:21',
    hasInternal: false,
    name: 'dzaadz',
    scanParams: {
      credentials: [],
      scenarios: [2],
      userAssets: [
        {
          mail: 'cristobal@x-rator.com',
          name: 'Cristobal',
        },
      ],
    },
    startDate: '2022-07-14',
    startTime: '03:19',
    type: typeBasedOnArg,
  }
}
